services:
  myservice:
    image: pythonf/mlflow:latest
    ports:
      - "5000:5000"
    healthcheck:
      test: curl --fail http://localhost:5000/health || exit 1
      interval: 10s
      timeout: 5s
      retries: 5